# Generated by Django 3.2.12 on 2022-05-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='管理员账号')),
                ('password', models.CharField(max_length=32, verbose_name='管理员密码')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='管理员电话号码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='管理员账号创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='管理员账号修改时间')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='题目标题')),
                ('content', models.TextField(max_length=1000, verbose_name='题目内容')),
                ('image', models.CharField(blank=True, max_length=128, null=True, verbose_name='图片路径')),
                ('accessory', models.CharField(blank=True, max_length=128, null=True, verbose_name='附件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='题目发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='题目修改时间')),
                ('publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='question_checker', to='adminapp.admin', verbose_name='题目发布人')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='公告标题')),
                ('content', models.TextField(max_length=1024, verbose_name='公告内容')),
                ('image', models.CharField(blank=True, max_length=128, null=True, verbose_name='图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='公告创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='公告修改时间')),
                ('accessory', models.CharField(blank=True, max_length=128, null=True, verbose_name='附件路径')),
                ('publisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='announcement_checker', to='adminapp.admin', verbose_name='公告发布人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcement',
            },
        ),
    ]
