# Generated by Django 3.2.12 on 2022-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_announcement_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='accessory',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='uploads/', verbose_name='附件'),
        ),
    ]
