# Generated by Django 3.2.12 on 2022-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_announcement_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'files_storage',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='question',
            name='accessory',
        ),
    ]
