# Generated by Django 3.2.12 on 2022-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20220510_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.IntegerField(choices=[(1, '未提交作品'), (2, '已提交作品'), (3, '成绩已公布')], default=1),
        ),
    ]
