# Generated by Django 3.2.12 on 2022-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_team_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='申请时间'),
        ),
    ]
