# Generated by Django 3.2.12 on 2022-05-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_application_student_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='student_type',
            new_name='application_type',
        ),
    ]
