# Generated by Django 3.2.12 on 2022-05-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_auto_20220517_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='comment_count',
        ),
    ]
